app/forms/chat.py
import re
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    SubmitField,
    ValidationError,
    FileField,
)
from wtforms.validators import DataRequired
from flask_login import current_user

from app import models as m
from app.database import db


class ChatFileUploadForm(FlaskForm):
    ticket_unique_id = StringField("ticket_unique_id", [DataRequired()])
    room_unique_id = StringField("room_unique_id", [DataRequired()])
    user_unique_id = StringField("user_unique_id", [DataRequired()])
    file = FileField("file", [DataRequired()])
    submit = SubmitField("Send verification code")


class ChatPhoneForm(FlaskForm):
    phone = StringField("phone", [DataRequired()])
    submit = SubmitField("Save")

    def validate_phone(self, field):
        pattern = r"^\+?\d{10,13}$"
        match_pattern = re.search(pattern, field.data)
        if not match_pattern:
            raise ValidationError("Invalid phone number.")

        query = m.User.select().where(m.User.phone == field.data).where(m.User.id != current_user.id)
        if db.session.scalar(query):
            raise ValidationError("This phone is already registered.")


class ChatAuthPasswordForm(FlaskForm):
    ticket_unique_id = StringField("ticket_unique_id")
    room_unique_id = StringField("room_unique_id", [DataRequired()])
    user_unique_id = StringField("user_unique_id", [DataRequired()])
    password = StringField("password", [DataRequired()])
    submit = SubmitField("Send verification code")

app/controllers/chat.py
import sqlalchemy as sa
from flask import current_app as app, render_template
from app.database import db
from app import models as m, schema as s, controllers as c
from app.logger import log


def get_home(user_message: str, room: m.Room) -> str:
    """
    The function to get chat home page.
    """
    log(log.INFO, "Chat home page")
    return render_template(
        "chat/chat_home.html",
        now=c.utcnow_chat_format(),
        room=room,
    )


def get_room(room_unique_id: str) -> m.Room:
    room_query = sa.select(m.Room).where(m.Room.unique_id == room_unique_id)
    room = db.session.scalar(room_query)

    if not room:
        raise ValueError(f"Room not found: {room_unique_id}")

    return room


def validate_event_sell_params(request_args) -> s.ChatSellEventParams:
    """
    The function to validate chat input params.
    """
    try:
        params = s.ChatSellEventParams.model_validate(dict(request_args))
    except Exception as e:
        raise ValueError(f"Invalid event params: {e}")

    return params


def validate_event_buy_params(request_args) -> s.ChatBuyEventParams:
    """
    The function to validate chat input params.
    """
    try:
        params = s.ChatBuyEventParams.model_validate(dict(request_args))
    except Exception as e:
        raise ValueError(f"Invalid event params: {e}")

    return params


def validate_cell_ticket_params(request_args) -> s.ChatSellTicketParams:
    """
    The function to validate chat input params.
    """
    try:
        params = s.ChatSellTicketParams.model_validate(dict(request_args))
    except Exception as e:
        raise ValueError(f"Invalid ticket params: {e}")

    return params


def validate_buy_ticket_params(request_args) -> s.ChatBuyTicketParams:
    """
    The function to validate chat input params.
    """
    try:
        params = s.ChatBuyTicketParams.model_validate(dict(request_args))
    except Exception as e:
        raise ValueError(f"Invalid ticket params: {e}")

    return params


def validate_auth_params(request_args) -> s.ChatAuthParams:
    """
    The function to validate chat input params.
    """
    try:
        params = s.ChatAuthParams.model_validate(dict(request_args))
    except Exception as e:
        raise ValueError(f"Invalid auth params: {e}")

    return params


def save_message(bot_message: str, user_message: str, room: m.Room):
    """
    The function to save message for history in chat.
    It is save message from chat-bot and user.
    """
    m.Message(
        sender_id=app.config["CHAT_DEFAULT_BOT_ID"],
        room_id=room.id,
        text=bot_message,
    ).save(False)
    m.Message(
        room_id=room.id,
        text=user_message,
    ).save()

    log(log.INFO, "Messages for history saved. Bot: [%s], user: [%s]", bot_message, user_message)


def ticket_details(ticket: m.Ticket, room: m.Room, buy=False) -> bool:
    date_time = ticket.event.date_time.strftime("%Y-%m-%d %H:%M") if ticket.event.date_time else ""
    ticket_details = (
        f"Event: {ticket.event.name}\n"
        + f"Location: {ticket.event.location.name}\n"
        + f"Venue: {ticket.event.venue}\n"
        + f"Date time: {date_time}\n"
        + f"Ticket type: {ticket.ticket_type}\n"
        + f"Ticket category: {ticket.ticket_category}\n"
        + f"Ticket section: {ticket.section}\n"
        + f"Ticket price net: {ticket.price_net}\n"
        + f"Ticket price gross: {ticket.price_gross}\n"
        + f"Ticket description: {ticket.description}\n"
    )
    if buy:
        c.save_message("We have found tickets. What ticket do you want?", f"Ticket details: \n{ticket_details}", room)
    else:
        c.save_message(ticket_details, "Got it", room)

    return True

app/views/chat.py
from datetime import datetime
import re
import os
from urllib.parse import urlparse
from flask import request, Blueprint, render_template, current_app as app
from flask_login import current_user, login_user
from app import models as m, db
from app.logger import log
from config import config

CFG = config()

chat_blueprint = Blueprint("chat", __name__, url_prefix="/chat")


@chat_blueprint.route("/sell", methods=["GET", "POST"])
def sell():
    now = datetime.now()
    now_str = now.strftime("%Y-%m-%d %H:%M")

    question = "Are you looking for buying or selling tickets or for events information?"

    seller_id = current_user.id if current_user.is_authenticated else None
    room = m.Room(
        seller_id=seller_id,
        buyer_id=app.config["CHAT_DEFAULT_BOT_ID"],
    ).save()
    m.Message(
        sender_id=app.config["CHAT_DEFAULT_BOT_ID"],
        room_id=room.id,
        text=question,
    ).save(False)
    m.Message(
        sender_id=seller_id,
        room_id=room.id,
        text="Selling",
    ).save(False)
    db.session.commit()

    if current_user.is_authenticated:
        template = "chat/sell/01_event_name.html"
    else:
        template = "chat/sell/chat_01_username.html"

    return render_template(
        "chat/registration/01_username.html",
        now=now_str,
        room=room,
    )


@chat_blueprint.route("/username", methods=["GET", "POST"])
def username():
    now = datetime.now()
    now_str = now.strftime("%Y-%m-%d %H:%M")

    room_unique_id = request.args.get("room_unique_id")
    user_name = request.args.get("chat_username")

    if not user_name or not room_unique_id:
        log(log.ERROR, "Form submitting error")
        return render_template(
            "chat/chat_error.html",
            error_message="Form submitting error",
        )

    room_query = m.Room.select().where(m.Room.unique_id == room_unique_id)
    room: m.Room = db.session.scalar(room_query)

    if not room:
        log(log.ERROR, "Room not found")
        return render_template(
            "chat/chat_error.html",
            error_message="Room not found",
        )

    user_query = m.User.select().where(m.User.username == user_name)
    user: m.User = db.session.scalar(user_query)

    if user:
        log(log.ERROR, "User already exists")
        return render_template(
            "chat/registration/01_username.html",
            error_message="User already exists",
            room=room,
            now=now_str,
        )

    m.Message(
        sender_id=app.config["CHAT_DEFAULT_BOT_ID"],
        room_id=room.id,
        text="Then let's get started!",
    ).save(False)
    m.Message(
        sender_id=app.config["CHAT_DEFAULT_BOT_ID"],
        room_id=room.id,
        text="Please input your username",
    ).save(False)
    m.Message(
        room_id=room.id,
        text=user_name,
    ).save(False)

    picture_query = m.Picture.select().where(m.Picture.filename.ilike(f"%{'default_avatar'}%"))
    picture: m.Picture = db.session.scalar(picture_query)
    picture_id = picture.id if picture else None
    user = m.User(
        # Since in chat registration we get user's info step by step,
        # asking user to input credentials one by one,
        # we need to fill the rest of the fields with default values
        username=user_name,
        picture_id=picture_id,
        email=app.config["CHAT_DEFAULT_EMAIL"],
        phone=app.config["CHAT_DEFAULT_PHONE"],
        card=app.config["CHAT_DEFAULT_CARD"],
        password="",
    ).save(False)
    db.session.flush()
    room.seller_id = user.id
    db.session.commit()
    log(log.INFO, f"User {user_name} created")

    return render_template(
        "chat/registration/02_email.html",
        now=now_str,
        room=room,
        user=user,
    )


@chat_blueprint.route("/email", methods=["GET", "POST"])
def email():
    now = datetime.now()
    now_str = now.strftime("%Y-%m-%d %H:%M")

    room_unique_id = request.args.get("room_unique_id")
    email_input = request.args.get("chat_email")
    user_unique_id = request.args.get("user_unique_id")

    user_query = m.User.select().where(m.User.unique_id == user_unique_id)
    user: m.User = db.session.scalar(user_query)

    room_query = m.Room.select().where(m.Room.unique_id == room_unique_id)
    room: m.Room = db.session.scalar(room_query)

    if not email_input or not room_unique_id or not user_unique_id:
        log(log.ERROR, "Form submitting error")
        return render_template(
            "chat/chat_error.html",
            error_message="Form submitting error",
            room=room,
            now=now_str,
            user=user,
            email_input=email_input,
        )

    pattern = r"^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
    match_pattern = re.search(pattern, email_input)
    if not match_pattern:
        return render_template(
            "chat/registration/02_email.html",
            error_message="Invalid email format",
            room=room,
            now=now_str,
            user=user,
            email_input=email_input,
        )

    email_query = m.User.select().where(m.User.email == email_input)
    email: m.User = db.session.scalar(email_query)

    if email:
        log(log.ERROR, "Email already taken")
        return render_template(
            "chat/registration/02_email.html",
            error_message="Email already taken",
            room=room,
            now=now_str,
            user=user,
            email_input=email_input,
        )

    m.Message(
        sender_id=app.config["CHAT_DEFAULT_BOT_ID"],
        room_id=room.id,
        text="Please input your email",
    ).save(False)
    m.Message(
        room_id=room.id,
        text=email_input,
    ).save(False)
    user.email = str(email_input)  # mypy made me do it!
    db.session.commit()

    return render_template(
        "chat/registration/03_pass.html",
        now=now_str,
        room=room,
        user=user,
    )


@chat_blueprint.route("/password", methods=["GET", "POST"])
def password():
    now = datetime.now()
    now_str = now.strftime("%Y-%m-%d %H:%M")

    room_unique_id = request.args.get("room_unique_id")
    user_unique_id = request.args.get("user_unique_id")
    password = request.args.get("chat_password")
    confirm_password = request.args.get("chat_confirm_password")

    user_query = m.User.select().where(m.User.unique_id == user_unique_id)
    user: m.User = db.session.scalar(user_query)

    room_query = m.Room.select().where(m.Room.unique_id == room_unique_id)
    room: m.Room = db.session.scalar(room_query)

    if password != confirm_password:
        return render_template(
            "chat/registration/03_pass.html",
            now=now_str,
            room=room,
            user=user,
            error="Passwords don't match",
        )

    m.Message(
        sender_id=app.config["CHAT_DEFAULT_BOT_ID"],
        room_id=room.id,
        text="Please input your password",
    ).save(False)
    m.Message(
        room_id=room.id,
        text=password,
    ).save(False)
    user.password = password
    db.session.commit()

    return render_template(
        "chat/registration/04_phone.html",
        now=now_str,
        room=room,
        user=user,
    )


@chat_blueprint.route("/phone", methods=["GET", "POST"])
def phone():
    now = datetime.now()
    now_str = now.strftime("%Y-%m-%d %H:%M")

    room_unique_id = request.args.get("room_unique_id")
    phone_input = request.args.get("chat_phone")
    user_unique_id = request.args.get("user_unique_id")

    if not room_unique_id or not user_unique_id:
        log(log.ERROR, "Form submitting error")
        return render_template(
            "chat/chat_error.html",
            error_message="Form submitting error",
        )

    user_query = m.User.select().where(m.User.unique_id == user_unique_id)
    user: m.User = db.session.scalar(user_query)

    room_query = m.Room.select().where(m.Room.unique_id == room_unique_id)
    room: m.Room = db.session.scalar(room_query)

    pattern = r"^\+?\d{10,13}$"
    match_pattern = re.search(pattern, str(phone_input))

    if not phone_input or not match_pattern:
        return render_template(
            "chat/registration/04_phone.html",
            now=now_str,
            room=room,
            user=user,
        )

    phone_query = m.User.select().where(m.User.phone == phone_input)
    phone: m.User = db.session.scalar(phone_query)

    if phone:
        log(log.ERROR, "Phone already taken")
        return render_template(
            "chat/registration/04_phone.html",
            error_message="Phone already taken",
            room=room,
            now=now_str,
            user=user,
            phone_input=phone_input,
        )

    # parse url and get the domain name

    # TODO: add production url
    if os.environ.get("APP_ENV") == "development":
        parsed_url = urlparse(request.base_url)
        profile_url = f"{parsed_url.scheme}://{parsed_url.netloc}/user/profile"
    else:
        base_url = app.config["STAGING_BASE_URL"]
        profile_url = f"{base_url}user/profile"

    success_message = "Você foi registrado com sucesso. Por favor, verifique seu perfil."

    login_user(user)

    m.Message(
        sender_id=app.config["CHAT_DEFAULT_BOT_ID"],
        room_id=room.id,
        text="Please input your phone",
    ).save(False)
    m.Message(
        room_id=room.id,
        text=phone_input,
    ).save(False)
    m.Message(
        sender_id=app.config["CHAT_DEFAULT_BOT_ID"],
        room_id=room.id,
        text=success_message,
    ).save(False)
    user.phone = str(phone_input)  # mypy made me do it!
    db.session.commit()

    return render_template(
        "chat/registration/05_verified.html",
        now=now_str,
        room=room,
        user=user,
        profile_url=profile_url,
    )

app/views/chat/__init__.py
# ruff: noqa: F401
from .main import chat_blueprint
from .auth import auth_blueprint
from .buy import buy_blueprint
from .sell import sell_blueprint
from .disputes import disputes_blueprint

chat_blueprint.register_blueprint(auth_blueprint)
chat_blueprint.register_blueprint(buy_blueprint)
chat_blueprint.register_blueprint(sell_blueprint)
chat_blueprint.register_blueprint(disputes_blueprint)

app/views/chat/buy/__init__.py
# ruff: noqa: F401
from .buy import buy_blueprint
from .ticket import ticket_blueprint
from .payment import payment_blueprint

buy_blueprint.register_blueprint(ticket_blueprint)
buy_blueprint.register_blueprint(payment_blueprint)

app/views/chat/sell/__init__.py
# ruff: noqa: F401
from .sell import sell_blueprint
from .ticket import ticket_blueprint
from .ticket_details import ticket_details_blueprint

sell_blueprint.register_blueprint(ticket_blueprint)
sell_blueprint.register_blueprint(ticket_details_blueprint)

app/templates/chat/chat_01.html
<div>
    {% for message in room.messages %}
    {% if message.sender_id == 2 %}
    {% set user_name = 'FanTicket' %}
    {% set background_color = 'bg-secondary' %}
    {% set justify = 'justify-end' %}
    {% else %}
    {% if current_user.is_authenticated %}
    {% set user_name = current_user.username %}
    {% else %}
    {% set user_name = 'Guest' %}
    {% endif %}
    {% set background_color = 'bg-white' %}
    {% endif %}
    <div class="flex text-white {{justify}}">
        <small class="pt-1">{{ user_name }} {{ cut_seconds(message.created_at) }}</small>
    </div>

    <div class="flex text-black {{justify}}">
        <p class="w-5/6 p-2 mb-2 rounded-lg {{background_color}}">
            {{message.text }}
        </p>
    </div>
    {% endfor %}

    <div class="flex text-white justify-end">
        <small class="pt-1">FanTicket {{ now }}</small>
    </div>

    <div class="mb-8 flex text-black justify-end">
        <p class="w-5/6 p-2 mb-2 rounded-lg bg-secondary">
            Then let's get started!
        </p>
    </div>

    {% if current_user.is_authenticated %}
    <p></p>
    {% else %}
    <div class="mt-2 flex justify-around">
        <input type="hidden" value="{{ room.unique_id }}">
        <input type="text" name="chat_username" class="border border-white bg-transparent rounded-lg">
        <button type="button" hx-get="{{ url_for('chat.username') }}" hx-target="#chat-window" hx-swap="innerHTML"
            hx-trigger="click" hx-include="{{ all_filters }}"
            class="p-2 text-center text-grey border border-r-grey rounded-xl hover:bg-gray-200 hover:text-black active:bg-gray-400">
            Submit
        </button>
    </div>
    {% endif %}
</div>

app/templates/chat/chat_02.html
<div>
    {% for message in room.messages %}
    {% if message.sender_id == 2 %}
    {% set user_name = 'FanTicket' %}
    {% set background_color = 'bg-secondary' %}
    {% set justify = 'justify-end' %}
    {% else %}
    {% if current_user.is_authenticated %}
    {% set user_name = current_user.username %}
    {% else %}
    {% set user_name = 'Guest' %}
    {% endif %}
    {% set background_color = 'bg-white' %}
    {% endif %}
    <div class="flex text-white {{justify}}">
        <small class="pt-1">{{ user_name }} {{ cut_seconds(message.created_at) }}</small>
    </div>

    <div class="flex text-black {{justify}}">
        <p class="w-5/6 p-2 mb-2 rounded-lg {{background_color}}">
            {{message.text }}
        </p>
    </div>
    {% endfor %}

    <div class="flex text-white justify-end">
        <small class="pt-1">FanTicket {{ now }}</small>
    </div>

    <div class="mb-8 flex text-black justify-end">
        <p class="w-5/6 p-2 mb-2 rounded-lg bg-secondary">
            Please input your email
        </p>
    </div>

    {% set all_filters = "[name='chat_email'], [name='room_unique_id']" %}
    {% if current_user.is_authenticated %}
    <p></p>
    {% else %}
    <div class="mt-2 flex justify-around">
        <input type="hidden" name="room_unique_id" value="{{ room.unique_id }}">
        <input type="email" name="chat_email" class="border border-white bg-transparent rounded-lg">
        <button type="button" hx-get="{{ url_for('chat.username') }}" hx-target="#chat-window" hx-swap="innerHTML"
            hx-trigger="click" hx-include="{{ all_filters }}"
            class="p-2 text-center text-grey border border-r-grey rounded-xl hover:bg-gray-200 hover:text-black active:bg-gray-400">
            Submit
        </button>
    </div>
    {% endif %}
</div>

app/templates/chat/chat_auth.html
{% from 'chat/_macros_chat_message.html' import bot_message, user_message, submit_message_get %}

<div id="chat-main" class="py-3 px-4  flex-col justify-start items-stretch overflow-y-scroll">
  {% include 'chat/chat_messages.html' %}
  {% include 'chat/chat_spinner.html' %}

  <input type="hidden" name="room_unique_id" value="{{ room.unique_id }}" />
  <input type="hidden" name="from_sign_up" value="True" />
  {% set all_filters = "[name='from_sign_up'], [name='room_unique_id'], [name='user_unique_id']" %}

  {% set html_element %}
  <div class="mt-2 flex gap-2">
    <button type="button" id="chat-window-buy" hx-get="{{ url_for('chat.auth.login_email') }}" hx-target="#chat-body"
      hx-swap="innerHTML" hx-trigger="click" hx-include="{{ all_filters }}"
      class="link p-2 w-full text-center text-secondary border border-secondary rounded-2xl transition-colors duration-200">
      Log in
    </button>
    <button type="button" id="chat-window-events" hx-get="{{ url_for('chat.auth.user_email.create') }}"
      hx-target="#chat-body" hx-swap="innerHTML" hx-trigger="click" hx-include="{{ all_filters }}"
      class="link p-2 w-full text-center text-secondary border border-secondary rounded-2xl transition-colors duration-200">
      Sign up
    </button>
  </div>
  {% endset %}

  <div id="chat-message-container" data-send-message>
    {% if error_message %}
    {% include 'chat/chat_message_error.html' %}
    {% endif %}

    {{ bot_message(pt('You do not log in. Please log in or sign up', 'chat_auth'), html_element) }}

    <div id="chat-message-spinner" class="htmx-indicator flex gap-2 justify-start">
      {% include 'chat/chat_spinner_active.html' %}
    </div>
  </div>
</div>

{{ submit_message_get('chat.sell', disabled='disabled') }}

{% block scripts %}
<!-- prettier-ignore -->
<script src="{{ url_for('static', filename='js/chat.js') }}" type="text/javascript" defer></script>
{% endblock %}

app/templates/chat/chat_bot_close.html
{% from 'chat/_macros_chat_message.html' import bot_message,
bot_message_without_date, user_message, submit_message_disable %}

<div id="chat-main" class="bot-message eveny py-3 px-4  flex-col justify-start items-stretch overflow-y-scroll">
  {% include 'chat/chat_messages.html' %} {% include 'chat/chat_spinner.html' %}

  <div id="chat-bot-close"></div>

  <div id="chat-message-container" data-send-message>
    {% if error_message %}
    {% include 'chat/chat_message_error.html' %}
    {% else%}
    {% if current_user.is_authenticated %}
    {{ bot_message("Thank you for using FanTicket. Conversation has been cleared and sent to your email. Chat will close
    after 5 second") }}
    {% else %}
    {{ bot_message("Thank you for using FanTicket. Conversation has been cleared. Chat will close after 5 second") }}
    {% endif %}
    {%endif %}
  </div>
</div>

{{ submit_message_disable() }}

{% block scripts %}
<!-- prettier-ignore -->
<script src="{{ url_for('static', filename='js/chat.js') }}" type="text/javascript" defer></script>
{% endblock %}

app/templates/chat/chat_dispute_message.html
<!-- prettier-ignore -->
{% from 'chat/_macros_chat_message.html' import history_message_bot, history_message_user %}
<!-- prettier-ignore -->
<div class="new_message">
    {% if message.sender_id == get_chatbot_id() %}
        {{ history_message_bot(message.text) }} 
    {% elif message.sender_id == current_user.id %} 
        {{ history_message_user(message) }}
    {% else %} 
        {{ history_message_user(message, False) }} 
    {% endif %}
</div>

app/templates/chat/chat_error.html
<div class="chat-message">
  <div class="flex text-white justify-start">
    <small class="pt-1">FanTicket {{ now }}</small>
  </div>

  <div class="mb-8 flex text-black justify-start">
    <p class="w-5/6 p-2 mb-2 rounded-lg bg-secondary">
      Something went wrong. {{ error_message }}
    </p>
  </div>
</div>

app/templates/chat/chat_greeting.html
{% include 'chat/chat_spinner.html' %}

{% set html_element %}
<div class="mt-2 flex justify-stretch gap-2">
  <button type="button" id="chat-window-buy" hx-get="{{ url_for('chat.sell') }}" hx-target="#chat-body"
    hx-swap="innerHTML" hx-trigger="click" hx-include="[name='room_unique_id']"
    class="link p-2 w-full text-center text-secondary border border-secondary rounded-2xl transition-colors duration-200">
    Selling
  </button>
  <button type="button" id="chat-window-events" hx-get="{{ url_for('chat.buy') }}" hx-target="#chat-body"
    hx-swap="innerHTML" hx-trigger="click" hx-include="[name='room_unique_id']"
    class="link p-2 w-full text-center text-secondary border border-secondary rounded-2xl transition-colors duration-200">
    Buying
  </button>
</div>
{% endset %}

<div id="chat-message-container" data-send-message>
  {% if current_user.is_authenticated and current_user.name %}
  {{ bot_message(pt('Hi, ', "chat_home_hi") + current_user.name + pt('! How can I assist you
  today? Are you looking to buy or sell a ticket?', 'chat_home_authenticated'), html_element) }}
  {% else %}
  <!-- prettier ignore -->
  {{ bot_message(pt('Hello! Welcome to FanTicketBot. How can I assist you today? Are you looking to buy or sell a
  ticket?', "chat_home"), html_element) }}
  {% endif %}
</div>

app/templates/chat/chat_header.html
<!-- prettier-ignore -->
<div class="sticky top-0 sm:static sm:top-auto p-4 flex justify-between items-center rounded-t-2xl" id="chat-header">
  {% set all_filters = "[name='room_unique_id']" %}
  <button type="button" hx-get="{{ url_for('chat.home') }}" hx-target="#chat-body" hx-swap="innerHTML"
    hx-trigger="click" hx-include="{{ all_filters }}"
    class="p-3 z-50 w-14 h-14 rounded-50% bg-secondary hover:scale-110 transform transition-transform duration-300">
    <svg class="chat-icon-open  w-full h-full transform transition-all duration-500 fill-black"
      xmlns="http://www.w3.org/2000/svg" viewBox="0 0 28 32">
      <path
        d="M28 32s-4.714-1.855-8.527-3.34H3.437C1.54 28.66 0 27.026 0 25.013V3.644C0 1.633 1.54 0 3.437 0h21.125c1.898 0 3.437 1.632 3.437 3.645v18.404H28V32zm-4.139-11.982a.88.88 0 00-1.292-.105c-.03.026-3.015 2.681-8.57 2.681-5.486 0-8.517-2.636-8.571-2.684a.88.88 0 00-1.29.107 1.01 1.01 0 00-.219.708.992.992 0 00.318.664c.142.128 3.537 3.15 9.762 3.15 6.226 0 9.621-3.022 9.763-3.15a.992.992 0 00.317-.664 1.01 1.01 0 00-.218-.707z">
      </path>
    </svg>
    <span class="sr-only">Home</span>
  </button>
  <span id="chat-header-title" class="text-2xl">Chatbot</span>
  <button hx-get="{{ url_for('chat.close') }}" hx-target="#chat-body" hx-swap="innerHTML" hx-trigger="click"
    hx-indicator="#chat-message-spinner" hx-include="{{ all_filters }}" class="w-14 h-14 ">&#x2715;</button>
</div>

app/templates/chat/chat_sms.html
{% extends "landing/base.html" %}

{% block title %}Chat{% endblock %}

{% block content %}
{% set all_filters = "[name='chat_phone'], [name='room_unique_id'], [name='user_unique_id']" %}
<div class="mt-14 bg-black">
    <p>Testing SMS</p>
    <div class="mt-2 flex justify-around">
        <input type="phone" name="chat_phone" class="border border-white bg-transparent rounded-lg bg-gray-500">
        <button type="button" hx-get="{{ url_for('chat.sms') }}" hx-trigger="click" hx-include="{{ all_filters }}"
            class="p-2 text-center text-grey border border-r-grey rounded-xl hover:bg-gray-200 hover:text-black active:bg-gray-400">
            Submit
        </button>
    </div>
</div>
{% endblock %}