app/controllers/chat.py
import sqlalchemy as sa
from flask import current_app as app, render_template
from app.database import db
from app import models as m, schema as s, controllers as c
from app.logger import log


def get_home(user_message: str, room: m.Room) -> str:
    """
    The function to get chat home page.
    """
    log(log.INFO, "Chat home page")
    return render_template(
        "chat/chat_home.html",
        now=c.utcnow_chat_format(),
        room=room,
    )


def get_room(room_unique_id: str) -> m.Room:
    room_query = sa.select(m.Room).where(m.Room.unique_id == room_unique_id)
    room = db.session.scalar(room_query)

    if not room:
        raise ValueError(f"Room not found: {room_unique_id}")

    return room


def validate_event_sell_params(request_args) -> s.ChatSellEventParams:
    """
    The function to validate chat input params.
    """
    try:
        params = s.ChatSellEventParams.model_validate(dict(request_args))
    except Exception as e:
        raise ValueError(f"Invalid event params: {e}")

    return params


def validate_event_buy_params(request_args) -> s.ChatBuyEventParams:
    """
    The function to validate chat input params.
    """
    try:
        params = s.ChatBuyEventParams.model_validate(dict(request_args))
    except Exception as e:
        raise ValueError(f"Invalid event params: {e}")

    return params


def validate_cell_ticket_params(request_args) -> s.ChatSellTicketParams:
    """
    The function to validate chat input params.
    """
    try:
        params = s.ChatSellTicketParams.model_validate(dict(request_args))
    except Exception as e:
        raise ValueError(f"Invalid ticket params: {e}")

    return params


def validate_buy_ticket_params(request_args) -> s.ChatBuyTicketParams:
    """
    The function to validate chat input params.
    """
    try:
        params = s.ChatBuyTicketParams.model_validate(dict(request_args))
    except Exception as e:
        raise ValueError(f"Invalid ticket params: {e}")

    return params


def validate_auth_params(request_args) -> s.ChatAuthParams:
    """
    The function to validate chat input params.
    """
    try:
        params = s.ChatAuthParams.model_validate(dict(request_args))
    except Exception as e:
        raise ValueError(f"Invalid auth params: {e}")

    return params


def save_message(bot_message: str, user_message: str, room: m.Room):
    """
    The function to save message for history in chat.
    It is save message from chat-bot and user.
    """
    m.Message(
        sender_id=app.config["CHAT_DEFAULT_BOT_ID"],
        room_id=room.id,
        text=bot_message,
    ).save(False)
    m.Message(
        room_id=room.id,
        text=user_message,
    ).save()

    log(log.INFO, "Messages for history saved. Bot: [%s], user: [%s]", bot_message, user_message)


def ticket_details(ticket: m.Ticket, room: m.Room, buy=False) -> bool:
    date_time = ticket.event.date_time.strftime("%Y-%m-%d %H:%M") if ticket.event.date_time else ""
    ticket_details = (
        f"Event: {ticket.event.name}\n"
        + f"Location: {ticket.event.location.name}\n"
        + f"Venue: {ticket.event.venue}\n"
        + f"Date time: {date_time}\n"
        + f"Ticket type: {ticket.ticket_type}\n"
        + f"Ticket category: {ticket.ticket_category}\n"
        + f"Ticket section: {ticket.section}\n"
        + f"Ticket price net: {ticket.price_net}\n"
        + f"Ticket price gross: {ticket.price_gross}\n"
        + f"Ticket description: {ticket.description}\n"
    )
    if buy:
        c.save_message("We have found tickets. What ticket do you want?", f"Ticket details: \n{ticket_details}", room)
    else:
        c.save_message(ticket_details, "Got it", room)

    return True

app/views/chat.py
from datetime import datetime
import re
import os
from urllib.parse import urlparse
from flask import request, Blueprint, render_template, current_app as app
from flask_login import current_user, login_user
from app import models as m, db
from app.logger import log
from config import config

CFG = config()

chat_blueprint = Blueprint("chat", __name__, url_prefix="/chat")


@chat_blueprint.route("/sell", methods=["GET", "POST"])
def sell():
    now = datetime.now()
    now_str = now.strftime("%Y-%m-%d %H:%M")

    question = "Are you looking for buying or selling tickets or for events information?"

    seller_id = current_user.id if current_user.is_authenticated else None
    room = m.Room(
        seller_id=seller_id,
        buyer_id=app.config["CHAT_DEFAULT_BOT_ID"],
    ).save()
    m.Message(
        sender_id=app.config["CHAT_DEFAULT_BOT_ID"],
        room_id=room.id,
        text=question,
    ).save(False)
    m.Message(
        sender_id=seller_id,
        room_id=room.id,
        text="Selling",
    ).save(False)
    db.session.commit()

    if current_user.is_authenticated:
        template = "chat/sell/01_event_name.html"
    else:
        template = "chat/sell/chat_01_username.html"

    return render_template(
        "chat/registration/01_username.html",
        now=now_str,
        room=room,
    )


@chat_blueprint.route("/username", methods=["GET", "POST"])
def username():
    now = datetime.now()
    now_str = now.strftime("%Y-%m-%d %H:%M")

    room_unique_id = request.args.get("room_unique_id")
    user_name = request.args.get("chat_username")

    if not user_name or not room_unique_id:
        log(log.ERROR, "Form submitting error")
        return render_template(
            "chat/chat_error.html",
            error_message="Form submitting error",
        )

    room_query = m.Room.select().where(m.Room.unique_id == room_unique_id)
    room: m.Room = db.session.scalar(room_query)

    if not room:
        log(log.ERROR, "Room not found")
        return render_template(
            "chat/chat_error.html",
            error_message="Room not found",
        )

    user_query = m.User.select().where(m.User.username == user_name)
    user: m.User = db.session.scalar(user_query)

    if user:
        log(log.ERROR, "User already exists")
        return render_template(
            "chat/registration/01_username.html",
            error_message="User already exists",
            room=room,
            now=now_str,
        )

    m.Message(
        sender_id=app.config["CHAT_DEFAULT_BOT_ID"],
        room_id=room.id,
        text="Then let's get started!",
    ).save(False)
    m.Message(
        sender_id=app.config["CHAT_DEFAULT_BOT_ID"],
        room_id=room.id,
        text="Please input your username",
    ).save(False)
    m.Message(
        room_id=room.id,
        text=user_name,
    ).save(False)

    picture_query = m.Picture.select().where(m.Picture.filename.ilike(f"%{'default_avatar'}%"))
    picture: m.Picture = db.session.scalar(picture_query)
    picture_id = picture.id if picture else None
    user = m.User(
        # Since in chat registration we get user's info step by step,
        # asking user to input credentials one by one,
        # we need to fill the rest of the fields with default values
        username=user_name,
        picture_id=picture_id,
        email=app.config["CHAT_DEFAULT_EMAIL"],
        phone=app.config["CHAT_DEFAULT_PHONE"],
        card=app.config["CHAT_DEFAULT_CARD"],
        password="",
    ).save(False)
    db.session.flush()
    room.seller_id = user.id
    db.session.commit()
    log(log.INFO, f"User {user_name} created")

    return render_template(
        "chat/registration/02_email.html",
        now=now_str,
        room=room,
        user=user,
    )


@chat_blueprint.route("/email", methods=["GET", "POST"])
def email():
    now = datetime.now()
    now_str = now.strftime("%Y-%m-%d %H:%M")

    room_unique_id = request.args.get("room_unique_id")
    email_input = request.args.get("chat_email")
    user_unique_id = request.args.get("user_unique_id")

    user_query = m.User.select().where(m.User.unique_id == user_unique_id)
    user: m.User = db.session.scalar(user_query)

    room_query = m.Room.select().where(m.Room.unique_id == room_unique_id)
    room: m.Room = db.session.scalar(room_query)

    if not email_input or not room_unique_id or not user_unique_id:
        log(log.ERROR, "Form submitting error")
        return render_template(
            "chat/chat_error.html",
            error_message="Form submitting error",
            room=room,
            now=now_str,
            user=user,
            email_input=email_input,
        )

    pattern = r"^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"
    match_pattern = re.search(pattern, email_input)
    if not match_pattern:
        return render_template(
            "chat/registration/02_email.html",
            error_message="Invalid email format",
            room=room,
            now=now_str,
            user=user,
            email_input=email_input,
        )

    email_query = m.User.select().where(m.User.email == email_input)
    email: m.User = db.session.scalar(email_query)

    if email:
        log(log.ERROR, "Email already taken")
        return render_template(
            "chat/registration/02_email.html",
            error_message="Email already taken",
            room=room,
            now=now_str,
            user=user,
            email_input=email_input,
        )

    m.Message(
        sender_id=app.config["CHAT_DEFAULT_BOT_ID"],
        room_id=room.id,
        text="Please input your email",
    ).save(False)
    m.Message(
        room_id=room.id,
        text=email_input,
    ).save(False)
    user.email = str(email_input)  # mypy made me do it!
    db.session.commit()

    return render_template(
        "chat/registration/03_pass.html",
        now=now_str,
        room=room,
        user=user,
    )


@chat_blueprint.route("/password", methods=["GET", "POST"])
def password():
    now = datetime.now()
    now_str = now.strftime("%Y-%m-%d %H:%M")

    room_unique_id = request.args.get("room_unique_id")
    user_unique_id = request.args.get("user_unique_id")
    password = request.args.get("chat_password")
    confirm_password = request.args.get("chat_confirm_password")

    user_query = m.User.select().where(m.User.unique_id == user_unique_id)
    user: m.User = db.session.scalar(user_query)

    room_query = m.Room.select().where(m.Room.unique_id == room_unique_id)
    room: m.Room = db.session.scalar(room_query)

    if password != confirm_password:
        return render_template(
            "chat/registration/03_pass.html",
            now=now_str,
            room=room,
            user=user,
            error="Passwords don't match",
        )

    m.Message(
        sender_id=app.config["CHAT_DEFAULT_BOT_ID"],
        room_id=room.id,
        text="Please input your password",
    ).save(False)
    m.Message(
        room_id=room.id,
        text=password,
    ).save(False)
    user.password = password
    db.session.commit()

    return render_template(
        "chat/registration/04_phone.html",
        now=now_str,
        room=room,
        user=user,
    )


@chat_blueprint.route("/phone", methods=["GET", "POST"])
def phone():
    now = datetime.now()
    now_str = now.strftime("%Y-%m-%d %H:%M")

    room_unique_id = request.args.get("room_unique_id")
    phone_input = request.args.get("chat_phone")
    user_unique_id = request.args.get("user_unique_id")

    if not room_unique_id or not user_unique_id:
        log(log.ERROR, "Form submitting error")
        return render_template(
            "chat/chat_error.html",
            error_message="Form submitting error",
        )

    user_query = m.User.select().where(m.User.unique_id == user_unique_id)
    user: m.User = db.session.scalar(user_query)

    room_query = m.Room.select().where(m.Room.unique_id == room_unique_id)
    room: m.Room = db.session.scalar(room_query)

    pattern = r"^\+?\d{10,13}$"
    match_pattern = re.search(pattern, str(phone_input))

    if not phone_input or not match_pattern:
        return render_template(
            "chat/registration/04_phone.html",
            now=now_str,
            room=room,
            user=user,
        )

    phone_query = m.User.select().where(m.User.phone == phone_input)
    phone: m.User = db.session.scalar(phone_query)

    if phone:
        log(log.ERROR, "Phone already taken")
        return render_template(
            "chat/registration/04_phone.html",
            error_message="Phone already taken",
            room=room,
            now=now_str,
            user=user,
            phone_input=phone_input,
        )

    # parse url and get the domain name

    # TODO: add production url
    if os.environ.get("APP_ENV") == "development":
        parsed_url = urlparse(request.base_url)
        profile_url = f"{parsed_url.scheme}://{parsed_url.netloc}/user/profile"
    else:
        base_url = app.config["STAGING_BASE_URL"]
        profile_url = f"{base_url}user/profile"

    success_message = "Você foi registrado com sucesso. Por favor, verifique seu perfil."

    login_user(user)

    m.Message(
        sender_id=app.config["CHAT_DEFAULT_BOT_ID"],
        room_id=room.id,
        text="Please input your phone",
    ).save(False)
    m.Message(
        room_id=room.id,
        text=phone_input,
    ).save(False)
    m.Message(
        sender_id=app.config["CHAT_DEFAULT_BOT_ID"],
        room_id=room.id,
        text=success_message,
    ).save(False)
    user.phone = str(phone_input)  # mypy made me do it!
    db.session.commit()

    return render_template(
        "chat/registration/05_verified.html",
        now=now_str,
        room=room,
        user=user,
        profile_url=profile_url,
    )

app/views/chat/__init__.py
# ruff: noqa: F401
from .main import chat_blueprint
from .auth import auth_blueprint
from .buy import buy_blueprint
from .sell import sell_blueprint
from .disputes import disputes_blueprint

chat_blueprint.register_blueprint(auth_blueprint)
chat_blueprint.register_blueprint(buy_blueprint)
chat_blueprint.register_blueprint(sell_blueprint)
chat_blueprint.register_blueprint(disputes_blueprint)

app/views/chat/buy/__init__.py
# ruff: noqa: F401
from .buy import buy_blueprint
from .ticket import ticket_blueprint
from .payment import payment_blueprint

buy_blueprint.register_blueprint(ticket_blueprint)
buy_blueprint.register_blueprint(payment_blueprint)

app/views/chat/sell/__init__.py
# ruff: noqa: F401
from .sell import sell_blueprint
from .ticket import ticket_blueprint
from .ticket_details import ticket_details_blueprint

sell_blueprint.register_blueprint(ticket_blueprint)
sell_blueprint.register_blueprint(ticket_details_blueprint)

app/views/tickets.py
from typing import Any
from datetime import datetime
from flask import request, Blueprint, render_template
from app import models as m, db
from app import schema as s

from config import config

CFG = config()


tickets_blueprint = Blueprint("tickets", __name__, url_prefix="/tickets")


def get_all_tickets(filter: s.TicketFilter) -> list[m.Ticket]:
    tickets_query = m.Ticket.select()

    if filter.event_id:
        tickets_query = tickets_query.where(m.Ticket.event_id == filter.event_id)
    else:
        if filter.q:
            tickets_query = tickets_query.where(m.Ticket.event.has(m.Event.name.ilike(f"%{filter.q}%")))

        if filter.location:
            location_query = m.Location.select().where(m.Location.name == filter.location)
            location = db.session.scalar(location_query)
            tickets_query = tickets_query.where(m.Ticket.event.has(location_id=location.id))

        if filter.categories:
            tickets_query = tickets_query.filter(
                m.Ticket.event.has(m.Event.category.has(m.Category.name.in_(filter.categories)))
            )

        if filter.date_from:
            date_from = datetime.strptime(filter.date_from, CFG.DATE_PICKER_FORMAT)
            tickets_query = tickets_query.where(m.Ticket.event.has(m.Event.date_time >= date_from))
        if filter.date_to:
            date_to = datetime.strptime(filter.date_to, CFG.DATE_PICKER_FORMAT)
            tickets_query = tickets_query.where(m.Ticket.event.has(m.Event.date_time <= date_to))

    limit = filter.tickets_per_page + CFG.TICKETS_PER_PAGE
    if filter.tickets_number:
        limit = filter.tickets_number + CFG.TICKETS_PER_PAGE

    return db.session.scalars(tickets_query.limit(limit)).all()


@tickets_blueprint.route("/", methods=["GET", "POST"])
def get_all():
    data: dict[str, Any] = dict(request.args)
    data["categories"] = request.args.getlist("categories")
    filter = s.TicketFilter.model_validate(data)

    tickets = get_all_tickets(filter)

    if (
        filter.q
        or filter.location
        or filter.date_from
        or filter.date_to
        or filter.categories
        or filter.tickets_per_page
        or filter.tickets_number
    ):
        template = "tickets/tickets_list.html"
    else:
        template = "tickets/tickets.html"

    return render_template(
        template,
        tickets=tickets,
        tickets_number=len(tickets),
        categories=m.Category.all(),
        locations=m.Location.all(),
    )


@tickets_blueprint.route("/<ticket_unique_id>")
def get_ticket(ticket_unique_id: str):
    ticket_query = m.Ticket.select().where(m.Ticket.unique_id == ticket_unique_id)
    ticket = db.session.scalar(ticket_query)

    return render_template("tickets/ticket.html", ticket=ticket)

app/templates/chat/sell/00_event_init.html
{% block links %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.1.1/datepicker.min.js" defer></script>
<link href="{{ url_for('static', filename='css/styles.css') }}" rel="stylesheet" />
{% endblock %}
{% set all_filters = "[name='event_name'], [name='room_unique_id'], [name='event_location'],
[name='event_category'], [name='event_date'], [name='event_url']" %}
<div>
  {% include 'chat/chat_messages.html' %}
  <div class="flex text-white justify-end">
    <small class="pt-1">FanTicket {{ now }}</small>
  </div>
  <div class="mb-2 flex text-black justify-end">
    <p class="w-5/6 p-2 rounded-t-lg rounded-bl-lg bg-secondary">
      What event are you selling tickets for?
    </p>
  </div>

  <div class="mb-8 flex text-black justify-end">
    <p class="w-5/6 p-2 rounded-t-lg rounded-bl-lg bg-secondary">
      Please, input location and date.
    </p>
  </div>

  <!--Filter Location -->
  <div class="relative">
    <button
      class="chat-filter-location-button w-full px-4 py-2 inline-flex justify-between items-center text-white bg-ultra-black border border-grey hover:bg-stone-900 focus:ring-4 focus:outline-none focus:ring-neutral-700 font-medium rounded-2xl text-sm text-center"
      type="button">
      <div class="flex gap-3 items-center">
        <!-- prettier-ignore -->
        <svg class="w-8 h-8" xmlns="http://www.w3.org/2000/svg" width="52" height="52" viewBox="0 0 52 52" fill="none">
          <rect x="1" y="1" width="50" height="50" rx="13" stroke="#F2B705" stroke-width="2" />
          <path
            d="M26.3333 26.6667C25.4493 26.6667 24.6014 26.3155 23.9763 25.6904C23.3512 25.0652 23 24.2174 23 23.3333C23 22.4493 23.3512 21.6014 23.9763 20.9763C24.6014 20.3512 25.4493 20 26.3333 20C27.2174 20 28.0652 20.3512 28.6904 20.9763C29.3155 21.6014 29.6667 22.4493 29.6667 23.3333C29.6667 23.7711 29.5804 24.2045 29.4129 24.6089C29.2454 25.0134 28.9999 25.3808 28.6904 25.6904C28.3808 25.9999 28.0134 26.2454 27.6089 26.4129C27.2045 26.5804 26.7711 26.6667 26.3333 26.6667ZM26.3333 14C23.858 14 21.484 14.9833 19.7337 16.7337C17.9833 18.484 17 20.858 17 23.3333C17 30.3333 26.3333 38 26.3333 38C26.3333 38 35.6667 30.3333 35.6667 23.3333C35.6667 20.858 34.6833 18.484 32.933 16.7337C31.1827 14.9833 28.8087 14 26.3333 14Z"
            fill="#F2B705" />
        </svg>
        <div>
          <p class="text-lg">Localização</p>
          <span id="chat-filter-location-status" class="text-grey">Selecione</span>
        </div>
      </div>
      <!-- prettier-ignore -->
      <svg class="w-2.5 h-2.5 ms-3" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none"
        viewBox="0 0 10 6">
        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4" />
      </svg>
    </button>
    <!-- Dropdown menu -->
    <div id="chat-filter-location-dropdown"
      class="chat-location-dropdown inset-x-0 mx-auto mt-2 p-1 text-white rounded-lg shadow">
      <input autocomplete="off" list="browsers" name="event_location"
        class="w-full h-9 p-2 text-white text-lg bg-middle-grey placeholder-gray-300 border-transparent outline-none focus:border-transparent focus:ring-0"
        list="events-filter-location-list" id="chat-filter-location-input" placeholder="choose location" />
      <datalist class=" inset-x-0 p-1 max-h-40 overflow-y-auto bg-datalist-location" id="chat-filter-location-list">
        {% for location in locations %}
        <option class="p-1 text-lg cursor-pointer bg-option-location hover:bg-light-grey" value="{{ location.name }}">
          {{ location.name }}
        </option>
        {% endfor %}
      </datalist>
    </div>
  </div>

  <!-- Filter Date -->
  <div class="relative">
    <!-- prettier-ignore -->
    <svg class="absolute top-1/2 -translate-y-1/2 ml-4 w-8 h-8" xmlns="http://www.w3.org/2000/svg" width="52"
      height="52" viewBox="0 0 52 52" fill="none">
      <rect x="1" y="1" width="50" height="50" rx="13" stroke="#F2B705" stroke-width="2" />
      <path fill-rule="evenodd" clip-rule="evenodd"
        d="M18.5581 14C19.0205 14 19.3953 14.3748 19.3953 14.8372V16.4806H22.6822V14.8372C22.6822 14.3748 23.057 14 23.5194 14C23.9818 14 24.3566 14.3748 24.3566 14.8372V16.4806H27.6434V14.8372C27.6434 14.3748 28.0182 14 28.4806 14C28.943 14 29.3178 14.3748 29.3178 14.8372V16.4806H32.6047V14.8372C32.6047 14.3748 32.9795 14 33.4419 14C33.9042 14 34.2791 14.3748 34.2791 14.8372V16.4806H34.6822C36.5146 16.4806 38 17.9661 38 19.7984V34.6822C38 36.5146 36.5146 38 34.6822 38H17.3178C15.4854 38 14 36.5146 14 34.6822V19.7984C14 17.9661 15.4854 16.4806 17.3178 16.4806H17.7209V14.8372C17.7209 14.3748 18.0958 14 18.5581 14ZM17.7209 18.155H17.3178C16.4102 18.155 15.6744 18.8908 15.6744 19.7984V22.6822H36.3256V19.7984C36.3256 18.8908 35.5898 18.155 34.6822 18.155H34.2791V18.5581C34.2791 19.0205 33.9042 19.3953 33.4419 19.3953C32.9795 19.3953 32.6047 19.0205 32.6047 18.5581V18.155H29.3178V18.5581C29.3178 19.0205 28.943 19.3953 28.4806 19.3953C28.0182 19.3953 27.6434 19.0205 27.6434 18.5581V18.155H24.3566V18.5581C24.3566 19.0205 23.9818 19.3953 23.5194 19.3953C23.057 19.3953 22.6822 19.0205 22.6822 18.5581V18.155H19.3953V18.5581C19.3953 19.0205 19.0205 19.3953 18.5581 19.3953C18.0958 19.3953 17.7209 19.0205 17.7209 18.5581V18.155ZM36.3256 24.3566H15.6744V34.6822C15.6744 35.5898 16.4102 36.3256 17.3178 36.3256H34.6822C35.5898 36.3256 36.3256 35.5898 36.3256 34.6822V24.3566Z"
        fill="#F2B705" />
    </svg>
    <input id="datepicker-filter" name="event_date" type="text"
      class="w-full h-14 pl-16 shadow-sm bg-ultra-black border border-grey text-white placeholder-white rounded-2xl hover:bg-stone-900 focus:ring-4 focus:outline-none focus:ring-neutral-700 block"
      placeholder="Data" />
    <!-- prettier-ignore -->
    <svg class="absolute top-1/2 -translate-y-1/2 right-0 mr-4 w-2.5 h-2.5 " aria-hidden="true"
      xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
      <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4" />
    </svg>
  </div>


  {% if error_message %}
  <div class="mb-8 mt-2 flex text-black justify-end">
    <p class="w-5/6 p-2 mb-2 rounded-t-lg rounded-bl-lg text-white bg-red-600">
      {{ error_message }}
    </p>
  </div>
  {% endif %}

  <div class="mt-4 flex justify-around">
    <input type="hidden" name="room_unique_id" value="{{ room.unique_id }}" />
    <button type="button" hx-get="{{ url_for('sell.get_events') }}" hx-target="#chat-body" hx-swap="innerHTML"
      hx-trigger="click" hx-include="{{ all_filters }}"
      class="p-2 w-full text-center text-grey border border-r-grey rounded-xl hover:bg-gray-200 hover:text-black active:bg-gray-400">
      Submit
    </button>
  </div>
</div>

{% block scripts %}
<!-- prettier-ignore -->
<script src="{{ url_for('static', filename='js/chat.js') }}" type="text/javascript" defer></script>
{% endblock %}

app/templates/chat/sell/chat_03_pass.html
<div>
  {% include 'chat/chat_messages.html' %}

  <div class="flex text-white justify-end">
    <small class="pt-1">FanTicket {{ now }}</small>
  </div>

  <div class="mb-8 flex text-black justify-end">
    {% if error %}
    <p class="w-5/6 p-2 mb-2 rounded-lg bg-secondary">{{ error }}</p>
    {% else %}
    <p class="w-5/6 p-2 mb-2 rounded-lg bg-secondary">
      Please input your password
    </p>
    {% endif %}
  </div>

  {% set all_filters = "[name='chat_password'], [name='chat_confirm_password'],
  [name='room_unique_id'], [name='user_unique_id']" %}
  {% if current_user.is_authenticated %}
  <p></p>
  {% else %}
  <div class="mt-2 flex justify-around">
    <input type="hidden" name="user_unique_id" value="{{ user.unique_id }}" />
    <input type="hidden" name="room_unique_id" value="{{ room.unique_id }}" />

    <div class="flex flex-col">
      <input type="password" name="chat_password" class="my-1 border border-white bg-transparent rounded-lg" />
      <input type="password" name="chat_confirm_password" class="my-1 border border-white bg-transparent rounded-lg" />
      <button type="button" hx-get="{{ url_for('chat.password') }}" hx-target="#chat-window" hx-swap="innerHTML"
        hx-trigger="click" hx-include="{{ all_filters }}"
        class="p-2 text-center text-grey border border-r-grey rounded-xl hover:bg-gray-200 hover:text-black active:bg-gray-400">
        Submit
      </button>
    </div>
  </div>
  {% endif %}
</div>

app/templates/chat/sell/chat_04_phone.html
<div>
  {% include 'chat/chat_messages.html' %}

  <div class="flex text-white justify-end">
    <small class="pt-1">FanTicket {{ now }}</small>
  </div>

  <div class="mb-8 flex text-black justify-end">
    <p class="w-5/6 p-2 mb-2 rounded-lg bg-secondary">
      Please input your phone
    </p>
  </div>

  {% if error_message %}
  <div class="mb-8 flex text-black justify-end">
    <p class="w-5/6 p-2 mb-2 rounded-lg text-white bg-red-600">
      {{ error_message }}: {{ phone_input }}
    </p>
  </div>
  {% endif %}

  {% set all_filters = "[name='chat_phone'], [name='room_unique_id'], [name='user_unique_id']" %}
  {% if current_user.is_authenticated %}
  <p></p>
  {% else %}
  <div class="mt-2 flex justify-around">
    <input type="hidden" name="user_unique_id" value="{{ user.unique_id }}" />
    <input type="hidden" name="room_unique_id" value="{{ room.unique_id }}" />
    <input type="phone" name="chat_phone" class="border border-white bg-transparent rounded-lg" />
    <button type="button" hx-get="{{ url_for('chat.phone') }}" hx-target="#chat-window" hx-swap="innerHTML"
      hx-trigger="click" hx-include="{{ all_filters }}"
      class="p-2 text-center text-grey border border-r-grey rounded-xl hover:bg-gray-200 hover:text-black active:bg-gray-400">
      Submit
    </button>
  </div>
  {% endif %}
</div>