app/models/payment.py
from typing import TYPE_CHECKING
from datetime import datetime
import sqlalchemy as sa
from sqlalchemy import orm
from app.database import db
from .utils import ModelMixin, utcnow


if TYPE_CHECKING:
    from .user import User
    from .ticket import Ticket


class Payment(db.Model, ModelMixin):
    __tablename__ = "payments"

    id: orm.Mapped[int] = orm.mapped_column(primary_key=True)
    buyer_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("users.id"))
    ticket_id: orm.Mapped[int] = orm.mapped_column(sa.ForeignKey("tickets.id"))
    description: orm.Mapped[str | None] = orm.mapped_column(sa.String(256))
    created_at: orm.Mapped[datetime] = orm.mapped_column(
        sa.DateTime,
        default=utcnow,
    )

    ticket: orm.Mapped["Ticket"] = orm.relationship(back_populates="payment")
    buyer: orm.Mapped["User"] = orm.relationship()

    @property
    def is_exist_dispute(self) -> bool:
        for room in self.ticket.rooms:
            if room.type_of == "dispute":
                return True
        return False

    @property
    def is_close_dispute(self) -> bool:
        for room in self.ticket.rooms:
            if room.type_of == "dispute" and not room.is_open:
                return True
        return False

    def __repr__(self):
        return f"<{self.id}:<{self.ticket}>|<{self.buyer.username}"

app/forms/chat.py
import re
from flask_wtf import FlaskForm
from wtforms import (
    StringField,
    SubmitField,
    ValidationError,
    FileField,
)
from wtforms.validators import DataRequired
from flask_login import current_user

from app import models as m
from app.database import db


class ChatFileUploadForm(FlaskForm):
    ticket_unique_id = StringField("ticket_unique_id", [DataRequired()])
    room_unique_id = StringField("room_unique_id", [DataRequired()])
    user_unique_id = StringField("user_unique_id", [DataRequired()])
    file = FileField("file", [DataRequired()])
    submit = SubmitField("Send verification code")


class ChatPhoneForm(FlaskForm):
    phone = StringField("phone", [DataRequired()])
    submit = SubmitField("Save")

    def validate_phone(self, field):
        pattern = r"^\+?\d{10,13}$"
        match_pattern = re.search(pattern, field.data)
        if not match_pattern:
            raise ValidationError("Invalid phone number.")

        query = m.User.select().where(m.User.phone == field.data).where(m.User.id != current_user.id)
        if db.session.scalar(query):
            raise ValidationError("This phone is already registered.")


class ChatAuthPasswordForm(FlaskForm):
    ticket_unique_id = StringField("ticket_unique_id")
    room_unique_id = StringField("room_unique_id", [DataRequired()])
    user_unique_id = StringField("user_unique_id", [DataRequired()])
    password = StringField("password", [DataRequired()])
    submit = SubmitField("Send verification code")

app/controllers/chat.py
import sqlalchemy as sa
from flask import current_app as app, render_template
from app.database import db
from app import models as m, schema as s, controllers as c
from app.logger import log


def get_home(user_message: str, room: m.Room) -> str:
    """
    The function to get chat home page.
    """
    log(log.INFO, "Chat home page")
    return render_template(
        "chat/chat_home.html",
        now=c.utcnow_chat_format(),
        room=room,
    )


def get_room(room_unique_id: str) -> m.Room:
    room_query = sa.select(m.Room).where(m.Room.unique_id == room_unique_id)
    room = db.session.scalar(room_query)

    if not room:
        raise ValueError(f"Room not found: {room_unique_id}")

    return room


def validate_event_sell_params(request_args) -> s.ChatSellEventParams:
    """
    The function to validate chat input params.
    """
    try:
        params = s.ChatSellEventParams.model_validate(dict(request_args))
    except Exception as e:
        raise ValueError(f"Invalid event params: {e}")

    return params


def validate_event_buy_params(request_args) -> s.ChatBuyEventParams:
    """
    The function to validate chat input params.
    """
    try:
        params = s.ChatBuyEventParams.model_validate(dict(request_args))
    except Exception as e:
        raise ValueError(f"Invalid event params: {e}")

    return params


def validate_cell_ticket_params(request_args) -> s.ChatSellTicketParams:
    """
    The function to validate chat input params.
    """
    try:
        params = s.ChatSellTicketParams.model_validate(dict(request_args))
    except Exception as e:
        raise ValueError(f"Invalid ticket params: {e}")

    return params


def validate_buy_ticket_params(request_args) -> s.ChatBuyTicketParams:
    """
    The function to validate chat input params.
    """
    try:
        params = s.ChatBuyTicketParams.model_validate(dict(request_args))
    except Exception as e:
        raise ValueError(f"Invalid ticket params: {e}")

    return params


def validate_auth_params(request_args) -> s.ChatAuthParams:
    """
    The function to validate chat input params.
    """
    try:
        params = s.ChatAuthParams.model_validate(dict(request_args))
    except Exception as e:
        raise ValueError(f"Invalid auth params: {e}")

    return params


def save_message(bot_message: str, user_message: str, room: m.Room):
    """
    The function to save message for history in chat.
    It is save message from chat-bot and user.
    """
    m.Message(
        sender_id=app.config["CHAT_DEFAULT_BOT_ID"],
        room_id=room.id,
        text=bot_message,
    ).save(False)
    m.Message(
        room_id=room.id,
        text=user_message,
    ).save()

    log(log.INFO, "Messages for history saved. Bot: [%s], user: [%s]", bot_message, user_message)


def ticket_details(ticket: m.Ticket, room: m.Room, buy=False) -> bool:
    date_time = ticket.event.date_time.strftime("%Y-%m-%d %H:%M") if ticket.event.date_time else ""
    ticket_details = (
        f"Event: {ticket.event.name}\n"
        + f"Location: {ticket.event.location.name}\n"
        + f"Venue: {ticket.event.venue}\n"
        + f"Date time: {date_time}\n"
        + f"Ticket type: {ticket.ticket_type}\n"
        + f"Ticket category: {ticket.ticket_category}\n"
        + f"Ticket section: {ticket.section}\n"
        + f"Ticket price net: {ticket.price_net}\n"
        + f"Ticket price gross: {ticket.price_gross}\n"
        + f"Ticket description: {ticket.description}\n"
    )
    if buy:
        c.save_message("We have found tickets. What ticket do you want?", f"Ticket details: \n{ticket_details}", room)
    else:
        c.save_message(ticket_details, "Got it", room)

    return True

app/views/chat/__init__.py
# ruff: noqa: F401
from .main import chat_blueprint
from .auth import auth_blueprint
from .buy import buy_blueprint
from .sell import sell_blueprint
from .disputes import disputes_blueprint

chat_blueprint.register_blueprint(auth_blueprint)
chat_blueprint.register_blueprint(buy_blueprint)
chat_blueprint.register_blueprint(sell_blueprint)
chat_blueprint.register_blueprint(disputes_blueprint)

app/views/chat/buy/__init__.py
# ruff: noqa: F401
from .buy import buy_blueprint
from .ticket import ticket_blueprint
from .payment import payment_blueprint

buy_blueprint.register_blueprint(ticket_blueprint)
buy_blueprint.register_blueprint(payment_blueprint)

app/views/chat/main.py
from datetime import datetime
from sqlalchemy import or_


from flask import request, Blueprint, render_template, current_app as app
from flask_login import current_user

from app import controllers as c
from app import schema as s
from app import models as m, db
from app.logger import log
from app import mail_controller
from app.controllers.jinja_globals import transactions_last_month
from config import config

CFG = config()

chat_blueprint = Blueprint("chat", __name__, url_prefix="/chat")


@chat_blueprint.route("/open", methods=["GET"])
def open():
    return render_template(
        "chat/chat_home.html",
        now=c.utcnow_chat_format(),
    )


@chat_blueprint.route("/close", methods=["GET"])
def close():
    room_unique_id = request.args.get("room_unique_id")
    if not room_unique_id:
        return render_template(
            "chat/chat_close.html",
            now=c.utcnow_chat_format(),
        )

    room = c.get_room(room_unique_id)

    if not room:
        return render_template(
            "chat/chat_error.html",
            error_message="Form submitting error",
            now=c.utcnow_chat_format(),
        )

    messages_query = m.Message.select().where(m.Message.room_id == room.id)
    messages = db.session.scalars(messages_query).all()

    if current_user.is_authenticated:
        mail_controller.send_email(
            (current_user,),
            f"Today's chat history {datetime.now().strftime(app.config['DATE_CHAT_HISTORY_FORMAT'])}",
            render_template(
                "email/chat_history.htm",
                user=current_user,
                messages=messages,
            ),
        )

    for message in messages:
        db.session.delete(message)
    db.session.commit()

    return render_template(
        "chat/chat_bot_close.html",
        now=c.utcnow_chat_format(),
        room=room,
    )


@chat_blueprint.route("/sell", methods=["GET", "POST"])
def sell():
    seller_id = current_user.id if current_user.is_authenticated else None
    room_unique_id = request.args.get("room_unique_id")
    renew_search = request.args.get("renew_search")
    save_history = request.args.get("save_history", False, type=bool)
    room = None
    template = "chat/chat_auth.html"

    if save_history:
        if not room_unique_id:
            log(log.ERROR, "room_unique_id is not provided")
            return render_template(
                "chat/chat_error.html",
                error_message="Form submitting error",
                now=c.utcnow_chat_format(),
            )
        room = c.get_room(room_unique_id)

        if not room:
            log(log.ERROR, "Room not found: [%s]", room_unique_id)
            return render_template(
                "chat/chat_error.html",
                error_message="Form submitting error",
                now=c.utcnow_chat_format(),
            )

        messages_query = m.Message.select().where(m.Message.room_id == room.id)
        messages = db.session.scalars(messages_query).all()

        if current_user.is_authenticated:
            mail_controller.send_email(
                (current_user,),
                f"Today's chat history {datetime.now().strftime(app.config['DATE_CHAT_HISTORY_FORMAT'])}",
                render_template(
                    "email/chat_history.htm",
                    user=current_user,
                    messages=messages,
                ),
            )

        for message in messages:
            db.session.delete(message)
        db.session.commit()

    if room_unique_id:
        room = c.get_room(room_unique_id)
        c.save_message(
            f"{current_user.name}, how can I assist you? Are you looking to buy or sell a ticket?",
            "Sell",
            room,
        )
    elif current_user.is_authenticated and (current_user.seller_chat_rooms or current_user.buyer_chat_rooms):
        rooms_query = (
            m.Room.select()
            .where(
                or_(m.Room.seller_id == current_user.id, m.Room.buyer_id == current_user.id),
                m.Room.type_of != m.RoomType.DISPUTE.value,
            )
            .order_by(m.Room.id.desc())
        )
        room = db.session.scalar(rooms_query)
    else:
        room = m.Room(
            seller_id=seller_id,
            buyer_id=app.config["CHAT_DEFAULT_BOT_ID"],
        ).save()
        assert room
        c.save_message(
            "Hello! Welcome to FanTicketBot. How can I assist you today? Are you looking to buy or sell a ticket?",
            "Sell",
            room,
        )
    assert room
    if renew_search:
        c.save_message("Choose action", "Renew search", room)
        log(log.ERROR, "Renew search")

    categories = []
    if current_user.is_authenticated and current_user.activated:
        template = "chat/sell/event_category.html"
        categories_query = m.Category.select().where(m.Category.deleted.is_(False))
        categories = db.session.scalars(categories_query).all()
    elif not current_user.is_authenticated:
        template = "chat/chat_auth.html"
    elif not current_user.activated and not current_user.identity_document:
        return render_template(
            "chat/registration/passport_identity_number.html",
            room=room,
            now=c.utcnow_chat_format(),
            user_unique_id=current_user.uuid,
        )
    elif not current_user.activated and not current_user.name:
        return render_template(
            "chat/registration/name.html",
            room=room,
            now=c.utcnow_chat_format(),
            user_unique_id=current_user.uuid,
        )
    elif not current_user.activated and not current_user.last_name:
        return render_template(
            "chat/registration/last_name.html",
            room=room,
            now=c.utcnow_chat_format(),
            user_unique_id=current_user.uuid,
        )
    elif not current_user.activated and not current_user.phone:
        return render_template(
            "chat/registration/phone.html",
            room=room,
            now=c.utcnow_chat_format(),
            user_unique_id=current_user.uuid,
        )
    elif not current_user.activated and not current_user.address:
        return render_template(
            "chat/registration/address.html",
            room=room,
            now=c.utcnow_chat_format(),
            user_unique_id=current_user.uuid,
        )
    elif not current_user.activated and not current_user.birth_date:
        return render_template(
            "chat/registration/birth_date.html",
            room=room,
            now=c.utcnow_chat_format(),
            user_unique_id=current_user.uuid,
        )

    if current_user.is_authenticated:
        global_fee_settings: m.GlobalFeeSettings = db.session.scalar(m.GlobalFeeSettings.select())
        if transactions_last_month(current_user) > global_fee_settings.selling_limit:
            return render_template(
                "chat/buy/transactions_limit.html",
                error_message="You have reached the limit of transactions per month",
                now=c.utcnow_chat_format(),
                room=room,
            )

    return render_template(
        template,
        locations=m.Location.all(),
        categories=categories,
        now=c.utcnow_chat_format(),
        room=room,
    )


@chat_blueprint.route("/buy")
def buy():
    room_unique_id = request.args.get("room_unique_id")
    save_history = request.args.get("save_history", False, type=bool)

    if save_history:
        if not room_unique_id:
            log(log.ERROR, "room_unique_id is not provided")
            return render_template(
                "chat/chat_error.html",
                error_message="Form submitting error",
                now=c.utcnow_chat_format(),
            )
        room = c.get_room(room_unique_id)

        if not room:
            log(log.ERROR, "Room not found: [%s]", room_unique_id)
            return render_template(
                "chat/chat_error.html",
                error_message="Form submitting error",
                now=c.utcnow_chat_format(),
            )

        messages_query = m.Message.select().where(m.Message.room_id == room.id)
        messages = db.session.scalars(messages_query).all()

        if current_user.is_authenticated:
            mail_controller.send_email(
                (current_user,),
                f"Today's chat history {datetime.now().strftime(app.config['DATE_CHAT_HISTORY_FORMAT'])}",
                render_template(
                    "email/chat_history.htm",
                    user=current_user,
                    messages=messages,
                ),
            )

        for message in messages:
            db.session.delete(message)
        db.session.commit()

    if room_unique_id:
        room = c.get_room(room_unique_id)
        c.save_message(
            f"{current_user.name}, how can I assist you? Are you looking to buy or sell a ticket?",
            "Buy",
            room,
        )
    else:
        room = m.Room(
            buyer_id=app.config["CHAT_DEFAULT_BOT_ID"],
        ).save()
        c.save_message(
            "Hello! Welcome to FanTicketBot. How can I assist you today? Are you looking to buy or sell a ticket?",
            "Buy",
            room,
        )

    locations = m.Location.all()
    messages = db.session.scalars(room.messages.select())

    return render_template(
        "chat/buy/event_name.html",
        locations=locations,
        now=c.utcnow_chat_format(),
        room=room,
        messages=messages,
    )


@chat_blueprint.route("/home")
def home():
    try:
        params = s.ChatAuthEmailParams.model_validate(dict(request.args))
    except Exception as e:
        log(log.ERROR, "Form submitting error: [%s]", e)
        return render_template(
            "chat/chat_error.html",
            error_message="Form submitting error",
            now=c.utcnow_chat_format(),
        )

    if not params.room_unique_id:

app/views/chat/sell/__init__.py
# ruff: noqa: F401
from .sell import sell_blueprint
from .ticket import ticket_blueprint
from .ticket_details import ticket_details_blueprint

sell_blueprint.register_blueprint(ticket_blueprint)
sell_blueprint.register_blueprint(ticket_details_blueprint)

app/templates/chat/buy/event_not_found.html
{% from 'chat/_macros_chat_message.html' import bot_message, bot_message_without_date, user_message,
submit_message_disable
%}

<div id="chat-main" class="py-3 px-4  flex-col justify-start items-stretch overflow-y-scroll">
  {% include 'chat/chat_messages.html' %}
  {% include 'chat/chat_spinner.html' %}

  {% set html_element %}
  {% set all_filters = "[name='room_unique_id'], [name='renew_search'], [name='event_unique_id']" %}
  <input type="hidden" name="room_unique_id" value="{{ room.unique_id }}" />
  <input type="hidden" name="event_unique_id" value="{{ event_unique_id }}" />
  <div class="mt-2 flex flex-col gap-2">
    <button type="button" hx-get="{{ url_for('chat.buy.get_event_name', renew_search=True) }}" hx-target="#chat-body"
      hx-swap="innerHTML" hx-trigger="click" hx-include="{{ all_filters }}"
      class="link p-2 w-full text-center text-secondary border border-secondary rounded-2xl transition-colors duration-200">
      Renew my search
    </button>
    <button type="button" hx-get="{{ url_for('chat.home') }}" hx-target="#chat-body" hx-swap="innerHTML"
      hx-trigger="click" hx-include="{{ all_filters }}"
      class="link p-2 w-full text-center text-secondary border border-secondary rounded-2xl transition-colors duration-200">
      End the conversation
    </button>
  </div>
  {% endset %}

  <div id="chat-message-container" data-send-message>
    {% if error_message %}
    {% include 'chat/chat_message_error.html' %}
    {% endif %}
    {{ bot_message(pt("Oops, it seems like there is no such event found😢 ", 'chat_buy_event_not_found'), html_element)
    }}

    <div id="chat-message-spinner" class="htmx-indicator flex gap-2 justify-start">
      {% include 'chat/chat_spinner_active.html' %}
    </div>
  </div>
</div>

{{ submit_message_disable() }}

{% block scripts %}
<!-- prettier-ignore -->
<script src="{{ url_for('static', filename='js/chat.js') }}" type="text/javascript" defer></script>
{% endblock %}

app/templates/chat/buy/payment.html
{% from 'chat/_macros_chat_message.html' import bot_message, bot_message_without_date, user_message,
submit_message_disable
%}

<div id="chat-main" class="py-3 px-4  flex-col justify-start items-stretch overflow-y-scroll">
  {% include 'chat/chat_messages.html' %}
  {% include 'chat/chat_spinner.html' %}

  {% set all_filters = "[name='room_unique_id'], [name='renew_search']" %}
  {% set html_element %}
  <input type="hidden" name="room_unique_id" value="{{ room.unique_id }}" />
  <div>
    <a href={{qr_url}}>
      <img class="w-full h-full" src="data:image/png;base64,{{ qr }}" alt="qr_code"></a>
  </div>
  <div class="mt-2 w-265 flex flex-col gap-3">
    <div class="flex flex-col gap-2">
      <button type="button" onclick="copyToClipboard('{{qr_to_copy}}')"
        class="link p-2 w-full text-center text-secondary border border-secondary rounded-2xl transition-colors duration-200">
        <div class="flex flex-col gap-1 justify-center items-center">
          <span>Copy code to clipboard</span>
        </div>
      </button>
    </div>
  </div>
  {% endset %}

  {% set html_element_end_conversation %}
  <div class="mt-2 w-265 flex flex-col gap-2">
    <button type="button" hx-get="{{ url_for('chat.close', save_history=True) }}" hx-target="#chat-body"
      hx-swap="innerHTML" hx-trigger="click" hx-include="{{ all_filters }}" hx-indicator="#chat-message-spinner"
      class="link p-2 w-full text-center text-secondary border border-secondary rounded-2xl transition-colors duration-200">
      End the conversation
    </button>
  </div>
  {% endset %}

  <div id="chat-message-container" data-send-message>
    {% if error_message %}
    {% include 'chat/chat_message_error.html' %}
    {% endif %}
    {{ bot_message("To proceed with the purchase, please scan QR code.") }}
    {{ bot_message_without_date(html_element=html_element) }}
    {{ bot_message("After payment is performed you will be able to see results in pagamentos section of your profile.")
    }}
    {{ bot_message_without_date(html_element=html_element_end_conversation) }}


    <div id="chat-message-spinner" class="htmx-indicator flex gap-2 justify-start">
      {% include 'chat/chat_spinner_active.html' %}
    </div>
  </div>
</div>


</div>
</div>

{{ submit_message_disable() }}

{% block scripts %}
<!-- prettier-ignore -->
<script src="{{ url_for('static', filename='js/chat.js') }}" type="text/javascript" defer></script>
<script>
  function copyToClipboard(string) {
    var input = document.createElement('input');
    input.value = string;
    document.body.appendChild(input);
    input.select();
    document.execCommand('copy');
    document.body.removeChild(input);
  }
</script>
{% endblock %}

app/templates/chat/buy/subscribe_success.html
{% from 'chat/_macros_chat_message.html' import bot_message, bot_message_without_date, user_message,
submit_message_disable
%}

<div id="chat-main" class="py-3 px-4  flex-col justify-start items-stretch overflow-y-scroll">
  {% include 'chat/chat_messages.html' %}
  {% include 'chat/chat_spinner.html' %}

  {% set html_element %}
  {% set all_filters = "[name='room_unique_id'], [name='renew_search'], [name='event_unique_id']" %}
  <input type="hidden" name="room_unique_id" value="{{ room.unique_id }}" />
  <input type="hidden" name="event_unique_id" value="{{ event_unique_id }}" />
  <div class="mt-2 flex flex-col gap-2">
    <!-- TODO: Add subscribe to event -->
    <button type="button" hx-get="{{ url_for('chat.buy.get_event_name', renew_search=True) }}" hx-target="#chat-body"
      hx-swap="innerHTML" hx-trigger="click" hx-include="{{ all_filters }}"
      class="link p-2 w-full text-center text-secondary border border-secondary rounded-2xl transition-colors duration-200">
      Renew my search
    </button>
    <button type="button" hx-get="{{ url_for('chat.home') }}" hx-target="#chat-body" hx-swap="innerHTML"
      hx-trigger="click" hx-include="{{ all_filters }}"
      class="link p-2 w-full text-center text-secondary border border-secondary rounded-2xl transition-colors duration-200">
      End the conversation
    </button>
  </div>
  {% endset %}

  <div id="chat-message-container" data-send-message>
    {% if error_message %}
    {% include 'chat/chat_message_error.html' %}
    {% endif %}
    {{ bot_message(pt("Thank you! Once we have tickets you will get notification to your email",
    'chat_buy_subscribe_success'), html_element) }}

    <div id="chat-message-spinner" class="htmx-indicator flex gap-2 justify-start">
      {% include 'chat/chat_spinner_active.html' %}
    </div>
  </div>
</div>

{{ submit_message_disable() }}

{% block scripts %}
<!-- prettier-ignore -->
<script src="{{ url_for('static', filename='js/chat.js') }}" type="text/javascript" defer></script>
{% endblock %}

app/templates/chat/buy/ticket_not_found.html
{% from 'chat/_macros_chat_message.html' import bot_message, bot_message_without_date, user_message,
submit_message_disable
%}

<div id="chat-main" class="py-3 px-4  flex-col justify-start items-stretch overflow-y-scroll">
  {% include 'chat/chat_messages.html' %}
  {% include 'chat/chat_spinner.html' %}

  {% set html_element %}
  {% set all_filters = "[name='room_unique_id'], [name='renew_search'], [name='event_unique_id']" %}
  <input type="hidden" name="room_unique_id" value="{{ room.unique_id }}" />
  <input type="hidden" name="event_unique_id" value="{{ event_unique_id }}" />
  <div class="mt-2 flex flex-col gap-2">
    <!-- TODO: Add subscribe to event -->
    <button type="button" hx-get="{{ url_for('chat.buy.subscribe_on_event') }}" hx-target="#chat-body"
      hx-swap="innerHTML" hx-trigger="click" hx-include="{{ all_filters }}"
      class="link p-2 w-full text-center text-secondary border border-secondary rounded-2xl transition-colors duration-200">
      Yes
    </button>
    <button type="button" hx-get="{{ url_for('chat.home') }}" hx-target="#chat-body" hx-swap="innerHTML"
      hx-trigger="click" hx-include="{{ all_filters }}"
      class="link p-2 w-full text-center text-secondary border border-secondary rounded-2xl transition-colors duration-200">
      No
    </button>
    <button type="button" hx-get="{{ url_for('chat.buy.get_event_name', renew_search=True) }}" hx-target="#chat-body"
      hx-swap="innerHTML" hx-trigger="click" hx-include="{{ all_filters }}"
      class="link p-2 w-full text-center text-secondary border border-secondary rounded-2xl transition-colors duration-200">
      Renew my search
    </button>
  </div>
  {% endset %}

  <div id="chat-message-container" data-send-message>
    {% if error_message %}
    {% include 'chat/chat_message_error.html' %}
    {% endif %}
    {{ bot_message(pt("Oops, it seems like we don´t have tickets for this event😢 Would you like to be notified if a
    ticket
    appears?", 'chat_buy_ticket_not_found_notify'), html_element) }}

    <div id="chat-message-spinner" class="htmx-indicator flex gap-2 justify-start">
      {% include 'chat/chat_spinner_active.html' %}
    </div>
  </div>
</div>

{{ submit_message_disable() }}

{% block scripts %}
<!-- prettier-ignore -->
<script src="{{ url_for('static', filename='js/chat.js') }}" type="text/javascript" defer></script>
{% endblock %}

app/templates/chat/buy/transactions_limit.html
{% from 'chat/_macros_chat_message.html' import bot_message, bot_message_without_date, user_message,
submit_message_disable %}

<div id="chat-main" class="py-3 px-4 h-475 flex-col justify-start items-stretch overflow-y-scroll">
  {% include 'chat/chat_messages.html' %}
  {% include 'chat/chat_spinner.html' %}

  {% if buying %}
  {% set route = 'chat.buy' %}
  {% else %}
  {% set route = 'chat.sell' %}
  {% endif %}

  {% set html_element %}
  {% set all_filters = "[name='room_unique_id'], [name='renew_search'], [name='event_unique_id']" %}
  <input type="hidden" name="room_unique_id" value="{{ room.unique_id }}" />
  <input type="hidden" name="event_unique_id" value="{{ event_unique_id }}" />
  <div class="mt-2 flex flex-col gap-2">
    <!-- TODO: Add subscribe to event -->

    <button type="button" hx-get="{{ url_for(route, renew_search=True) }}" hx-target="#chat-body" hx-swap="innerHTML"
      hx-trigger="click" hx-include="{{ all_filters }}"
      class="link p-2 w-full text-center text-secondary border border-secondary rounded-2xl transition-colors duration-200">
      Renew my input
    </button>
    <button type="button" hx-get="{{ url_for('chat.home') }}" hx-target="#chat-body" hx-swap="innerHTML"
      hx-trigger="click" hx-include="{{ all_filters }}"
      class="link p-2 w-full text-center text-secondary border border-secondary rounded-2xl transition-colors duration-200">
      End the conversation
    </button>
  </div>
  {% endset %}

  <div id="chat-message-container" data-send-message>
    {% if error_message %}
    {% include 'chat/chat_message_error.html' %}
    {% endif %}
    {{ bot_message(pt("Unfortunately in order to avoid frauds we have to limit transactions for this month.",
    'chat_buy_transactions_limit'), html_element)
    }}

    <div id="chat-message-spinner" class="htmx-indicator flex gap-2 justify-start">
      {% include 'chat/chat_spinner_active.html' %}
    </div>
  </div>
</div>

{{ submit_message_disable() }}

{% block scripts %}
<!-- prettier-ignore -->
<script src="{{ url_for('static', filename='js/chat.js') }}" type="text/javascript" defer></script>
{% endblock %}